"""tables

Revision ID: 69a7a9c28856
Revises: 
Create Date: 2024-03-12 20:23:22.322337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a7a9c28856'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('youtube_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=True),
    sa.Column('local_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_urls_local_url'), 'youtube_urls', ['local_url'], unique=False)
    op.create_index(op.f('ix_youtube_urls_url'), 'youtube_urls', ['url'], unique=False)
    op.create_index(op.f('ix_youtube_urls_video_id'), 'youtube_urls', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_urls_video_id'), table_name='youtube_urls')
    op.drop_index(op.f('ix_youtube_urls_url'), table_name='youtube_urls')
    op.drop_index(op.f('ix_youtube_urls_local_url'), table_name='youtube_urls')
    op.drop_table('youtube_urls')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
